name: CI Pipeline - SalonHub

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # ------------------------
  # CI: TESTING JOB
  # ------------------------
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ===== Backend =====
      - name: Install backend dependencies
        working-directory: Server
        run: npm install

      - name: Create backend .env
        working-directory: Server
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "BREVO_API=${{ secrets.BREVO_API }}" >> .env
          echo "BREVO_EMAIL=${{ secrets.BREVO_EMAIL }}" >> .env
          echo "BREVO_HOST=${{ secrets.BREVO_HOST }}" >> .env
          echo "BREVO_PASS=${{ secrets.BREVO_PASS }}" >> .env
          echo "BREVO_PORT=${{ secrets.BREVO_PORT }}" >> .env
          echo "BREVO_USER=${{ secrets.BREVO_USER }}" >> .env
          echo "CRON_SECRET=${{ secrets.CRON_SECRET }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGODB }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}" >> .env
          echo "RAZORPAY_SECRET=${{ secrets.RAZORPAY_SECRET }}" >> .env
          echo "NODE_ENV =${{ secrets.NODE_ENV }}" >> .env

      - name: Start backend
        working-directory: Server
        run: |
          npm run start &
          sleep 10

      # ===== Frontend =====
      - name: Install frontend dependencies
        working-directory: client
        run: npm install

      - name: Create frontend .env
        working-directory: client
        run: |
          echo "ITE_PROD_BASE_URL=${{ secrets.VITE_PROD_BASE_URL }}" >> .env
          echo "VITE_DEV_BASE_URL=${{ secrets.VITE_DEV_BASE_URL }}" >> .env
          echo "VITE_RAZORPAY_KEY_ID=${{ secrets.VITE_RAZORPAY_KEY_ID}}" >> .env
          echo "VITE_RAZORPAY_KEY_SECRET=${{ secrets.VITE_RAZORPAY_SECRET}}" >> .env

      - name: Install Playwright browsers
        working-directory: client
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: client
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
            name: playwright-report
            path: client/playwright-report

  # ------------------------
  # CD: FRONTEND → VERCEL
  # ------------------------
  deploy-frontend:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy frontend to Vercel
        uses: amondnet/vercel-action@v25
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ARGS: '--prod'

  # ------------------------
  # CD: BACKEND → AWS EC2
  # ------------------------
  deploy-backend:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd sbt/Server
            git pull origin main
            npm install
            pm2 restart salonhub-backend
